config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :username,
            presence: true,
            uniqueness: true,            
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was saved."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article was updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= form_with(model: @article, local: true) do |f|%>
  <div class="form-group row">
    <%= f.label :title, class: 'col-form-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group row">
    <%= f.label :description, class: 'col-form-label' %>
    <%= f.text_area :description, class: 'form-control', rows: 5 %>
  </div>
  <div class="form-group row">
    <%= link_to  "Cancel", articles_path, class: "btn btn-danger mr-2" %>
    <%= f.submit class:'btn btn-primary'%><br />
  </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
  <div class="container">
    <%= render  "shared/errors" %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow md-5 bg-white rounded">
          <div class="card-header">
            <h3>Edit an article</h3>

          </div>
          <div class="card-body">

            <%= render 'form' %>

          </div>
        </div>
      </div>
    </div>
  </div>

app/views/articles/index.html.erb
  <h1 class="text-center mt-4">Articles listing page</h1>
  <div class="container">
    <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow md-5 bg-white rounded">
          <div class="card-header">
            Featured
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: 'text-success' %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'Show', article_path(article), class: 'btn btn-primary'%>
            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary' %>
            <%= link_to 'Delete', article_path(article), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created at <%= time_ago_in_words(article.created_at) %>,
              edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <p>
      <%= link_to 'Home', root_path%>
      <%= link_to 'About', about_path%>
      <%= link_to 'Articles', articles_path%>
      <%= link_to 'New Articles', new_article_path%>
    </p>
  </div>

app/views/articles/new.html.erb
  <div class="container">
    <%= render  "shared/errors" %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow md-5 bg-white rounded">
          <div class="card-header">
            <h3>Create an article</h3>

          </div>
          <div class="card-body">

            <%= render 'form' %>

          </div>
        </div>
      </div>
    </div>
  </div>

app/views/articles/show.html.erb
<h1 class="text-center">Showing Article Details</h1>
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow md-5 bg-white rounded">
      <div class="card-header">
        Featured
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= @article.title %></h5>
        <div class="card-text text-left"><%= @article.description %></div>
        <%= link_to 'Articles', articles_path, class: 'btn btn-primary'%>
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary' %>
        <%= link_to 'Delete', article_path(@article), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
      </div>
      <div class="card-footer text-muted">
        <small>Created at <%= time_ago_in_words(@article.created_at) %>,
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Place sticky footer content here. &copy;</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 offset-xs-2">

      <div class="alert alert-success" role="alert">
        <%= msg %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%# <a id="logo" class="navbar-brand" href="#">Alpha Blog</a> %>
      <%= link_to  "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to  "New Article", new_article_path, class: 'dropdown-item' %>
              <%= link_to  "View Articles", articles_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Six</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">

  <%# <body> %>
  <%= render  "layouts/navigation" %>
  <%= render  "layouts/messages" %>
  <%= yield %>
  <%= render  "layouts/footer" %>
</body>

</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div id="home-container" class="container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="#" role="button">Sign Up</a>
    </div>

    <%= link_to 'About', about_path%>
    <%= link_to 'Articles', articles_path%>
  </div>
</div>

app/views/shared/_errors.html.erb
  <% if @article.errors.any? %>
  <div class="alert alert-danger mt-4" role="alert">
    <h2>Check the following errors</h2>
    <% @article.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
  </div>
  <% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>